### Libraries

In [1]:
import pandas as pd
import os
import kagglehub

c:\Python3.10\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [121]:
os.environ["KAGGLEHUB_CACHE"] = r"data\raw"

# Download latest version
path = kagglehub.dataset_download("akrambelha/global-e-commerce-dataset-1m-records-20242026")

print("Path to dataset files:", path)
df=pd.read_csv(os.path.join(path, "ecommerce_dataset_+1m.csv"))
df.to_csv(r"data\raw\ecommerce_dataset_+1m.csv")

Path to dataset files: data\raw/datasets/akrambelha/global-e-commerce-dataset-1m-records-20242026/versions/1

In [3]:
df.columns

Index(['Unnamed: 0', 'order_id', 'order_date', 'order_year', 'order_month',
       'order_day', 'order_hour', 'order_minute', 'order_second', 'is_weekend',
       'order_status', 'return_reason', 'customer_id', 'customer_name',
       'gender', 'age', 'customer_segment', 'country', 'city',
       'customer_loyalty_score', 'total_orders_by_customer',
       'account_creation_date', 'product_id', 'product_name', 'category',
       'sub_category', 'brand', 'product_rating_avg', 'product_reviews_count',
       'stock_quantity', 'unit_price_usd', 'quantity', 'discount_percent',
       'discount_amount_usd', 'total_price_usd', 'cost_usd', 'profit_usd',
       'tax_usd', 'currency', 'payment_method', 'payment_status',
       'installment_plan', 'shipping_method', 'shipping_cost_usd',
       'delivery_days', 'shipping_country', 'warehouse_location',
       'delivery_status', 'rating', 'review_sentiment', 'customer_feedback',
       'coupon_used', 'coupon_code', 'campaign_source', 'device_type',
       'traffic_source', 'session_duration_minutes', 'pages_visited',
       'abandoned_cart_before', 'fraud_risk_score', 'profit_margin_percent',
       'order_priority', 'support_ticket_created'],
      dtype='object')

In [33]:
df.shape

(1000123, 63)

In [4]:
# created new_df with my cols

w_cols = [
    'product_id',
    'product_name',
    'category',
    'sub_category',
    'brand',
    'product_rating_avg',
    'product_reviews_count',
    'stock_quantity',
    'fraud_risk_score',
    'support_ticket_created',
    'return_reason'
]

new_df = df[w_cols].copy()

new_df.head()

,product_id,product_name,category,sub_category,brand,product_rating_avg,product_reviews_count,stock_quantity,fraud_risk_score,support_ticket_created,return_reason
0,PRD-1FPK,Coffee Maker Automatic,Home,Kitchen,Nike,3.2,3112,99,45.3,Yes,NaN
1,PRD-C6UZ,Yoga Mat Non-Slip,Health,Supplements,Asus,3.8,3758,146,97.1,Yes,NaN
2,PRD-T2TA,Blender 1000W,Home,Furniture,Asus,3.0,2973,899,43.8,No,NaN
3,PRD-IROD,Badminton Racket,Sports,Accessories,Adidas,3.8,3825,884,96.9,Yes,NaN
4,PRD-LBR7,Screen Protector Tempered Glass,Electronics,Cameras,Anker,3.1,4160,82,45.8,Yes,NaN

In [5]:
new_df.columns

Index(['product_id', 'product_name', 'category', 'sub_category', 'brand',
       'product_rating_avg', 'product_reviews_count', 'stock_quantity',
       'fraud_risk_score', 'support_ticket_created', 'return_reason'],
      dtype='object')

In [6]:
len(new_df.columns)

11

In [7]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000123 entries, 0 to 1000122
Data columns (total 11 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   product_id              1000123 non-null  object
 1   product_name            1000123 non-null  object
 2   category                1000123 non-null  object
 3   sub_category            1000123 non-null  object
 4   brand                   1000123 non-null  object
 5   product_rating_avg      1000123 non-null  float64
 6   product_reviews_count   1000123 non-null  int64
 7   stock_quantity          1000123 non-null  int64
 8   fraud_risk_score        1000123 non-null  float64
 9   support_ticket_created  1000123 non-null  object
 10  return_reason           99879 non-null    object
dtypes: float64(2), int64(2), object(7)
memory usage: 83.9+ MB

In [8]:
new_df.isnull().sum()

product_id                     0
product_name                   0
category                       0
sub_category                   0
brand                          0
product_rating_avg             0
product_reviews_count          0
stock_quantity                 0
fraud_risk_score               0
support_ticket_created         0
return_reason             900244
dtype: int64

In [9]:
new_df['category'].value_counts()

category
Home           200589
Sports         200397
Electronics    200019
Health         199574
Clothing       199544
Name: count, dtype: int64

In [10]:
new_df[['category','sub_category']].value_counts().sort_index()

category     sub_category
Clothing     Accessories        39925
             Kids Wear          39789
             Mens Wear          39909
             Shoes              40036
             Womens Wear        39885
Electronics  Accessories        33294
             Audio              33340
             Cameras            33515
             Laptops            33232
             Smartphones        33265
             Tablets            33373
Health       Fitness            49567
             Medical Devices    49826
             Personal Care      50039
             Supplements        50142
Home         Appliances         39588
             Bedding            40105
             Decor              40507
             Furniture          40147
             Kitchen            40242
Sports       Accessories        50483
             Gym Equipment      50141
             Outdoor            49816
             Sports Wear        49957
Name: count, dtype: int64

In [11]:
new_df['category'].isnull().sum()
new_df['sub_category'].isnull().sum()

0

In [12]:
new_df.columns

Index(['product_id', 'product_name', 'category', 'sub_category', 'brand',
       'product_rating_avg', 'product_reviews_count', 'stock_quantity',
       'fraud_risk_score', 'support_ticket_created', 'return_reason'],
      dtype='object')

In [13]:
new_df

,product_id,product_name,category,sub_category,brand,product_rating_avg,product_reviews_count,stock_quantity,fraud_risk_score,support_ticket_created,return_reason
0,PRD-1FPK,Coffee Maker Automatic,Home,Kitchen,Nike,3.2,3112,99,45.3,Yes,NaN
1,PRD-C6UZ,Yoga Mat Non-Slip,Health,Supplements,Asus,3.8,3758,146,97.1,Yes,NaN
2,PRD-T2TA,Blender 1000W,Home,Furniture,Asus,3.0,2973,899,43.8,No,NaN
3,PRD-IROD,Badminton Racket,Sports,Accessories,Adidas,3.8,3825,884,96.9,Yes,NaN
4,PRD-LBR7,Screen Protector Tempered Glass,Electronics,Cameras,Anker,3.1,4160,82,45.8,Yes,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1000118,PRD-PHM3,Jump Rope Speed,Sports,Accessories,Dell,3.3,1311,551,99.8,Yes,NaN
1000119,PRD-T0M6,Baseball Cap,Clothing,Shoes,GoPro,3.6,1849,218,36.7,Yes,NaN
1000120,PRD-OAN2,Digital Thermometer,Health,Fitness,Logitech,3.8,2030,1000,51.2,Yes,NaN
1000121,PRD-71G1,Badminton Racket,Sports,Sports Wear,Samsung,3.2,4015,303,72.4,Yes,NaN
1000122,PRD-NBP2,Hooded Sweatshirt,Clothing,Shoes,Asus,3.1,3941,543,25.9,Yes,NaN

In [14]:
new_df[['product_id','product_name']]

        product_id                     product_name
0         PRD-1FPK           Coffee Maker Automatic
1         PRD-C6UZ                Yoga Mat Non-Slip
2         PRD-T2TA                    Blender 1000W
3         PRD-IROD                 Badminton Racket
4         PRD-LBR7  Screen Protector Tempered Glass
...            ...                              ...
1000118   PRD-PHM3                  Jump Rope Speed
1000119   PRD-T0M6                     Baseball Cap
1000120   PRD-OAN2              Digital Thermometer
1000121   PRD-71G1                 Badminton Racket
1000122   PRD-NBP2                Hooded Sweatshirt

[1000123 rows x 2 columns]

In [15]:
len(new_df)

1000123

In [16]:
ids = new_df.groupby("product_id")["product_name"].nunique()
ids = ids[ids > 1].index

new_df[new_df["product_id"].isin(ids)]

,product_id,product_name,category,sub_category,brand,product_rating_avg,product_reviews_count,stock_quantity,fraud_risk_score,support_ticket_created,return_reason
1,PRD-C6UZ,Yoga Mat Non-Slip,Health,Supplements,Asus,3.8,3758,146,97.1,Yes,NaN
2,PRD-T2TA,Blender 1000W,Home,Furniture,Asus,3.0,2973,899,43.8,No,NaN
3,PRD-IROD,Badminton Racket,Sports,Accessories,Adidas,3.8,3825,884,96.9,Yes,NaN
10,PRD-UHZ1,Massage Gun Deep Tissue,Health,Personal Care,Nikon,4.2,938,796,85.0,Yes,NaN
12,PRD-93KM,Treadmill Folding,Sports,Sports Wear,Xiaomi,4.4,1036,280,15.2,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1000111,PRD-F435,Jump Rope Speed,Sports,Outdoor,Adidas,3.5,4413,932,69.8,Yes,Better Price Elsewhere
1000112,PRD-4T9C,Smart Watch Series 8,Electronics,Cameras,Philips,3.4,1623,318,39.4,Yes,NaN
1000116,PRD-C8TB,Tennis Balls Pack,Sports,Sports Wear,Xiaomi,4.9,1285,100,91.3,No,NaN
1000118,PRD-PHM3,Jump Rope Speed,Sports,Accessories,Dell,3.3,1311,551,99.8,Yes,NaN
1000122,PRD-NBP2,Hooded Sweatshirt,Clothing,Shoes,Asus,3.1,3941,543,25.9,Yes,NaN

In [17]:
new_df.describe().round(2)

,product_rating_avg,product_reviews_count,stock_quantity,fraud_risk_score
count,1000123.00,1000123.00,1000123.00,1000123.00
mean,4.00,2501.57,499.81,49.96
std,0.58,1443.46,288.86,28.85
min,3.00,0.00,0.00,0.00
25%,3.50,1253.00,250.00,25.00
50%,4.00,2503.00,500.00,50.00
75%,4.50,3752.00,750.00,74.90
max,5.00,5000.00,1000.00,100.00

### list of product_id(s) with distinct product_name(s) count

In [18]:
test = new_df.groupby('product_id')["product_name"].nunique().loc[lambda x : x>1]
test

product_id
PRD-0000    3
PRD-0008    3
PRD-0009    2
PRD-000D    2
PRD-000F    3
           ..
PRD-ZZYG    2
PRD-ZZYT    2
PRD-ZZYV    2
PRD-ZZZC    4
PRD-ZZZG    2
Name: product_name, Length: 198892, dtype: int64

In [19]:
test.iloc[:].sum()

439243

In [20]:
new_df.sort_values("product_id").head(20)

,product_id,product_name,category,sub_category,brand,product_rating_avg,product_reviews_count,stock_quantity,fraud_risk_score,support_ticket_created,return_reason
6338,PRD-0000,USB-C Fast Charger 65W,Electronics,Accessories,Adidas,5.0,4062,894,2.7,Yes,NaN
339447,PRD-0000,Laptop Backpack Waterproof,Electronics,Cameras,Baseus,3.4,1818,377,22.0,Yes,NaN
402918,PRD-0000,Water Bottle Insulated,Sports,Sports Wear,JBL,4.7,4317,646,52.1,No,NaN
402234,PRD-0001,Hooded Sweatshirt,Clothing,Shoes,Huawei,4.1,4806,74,48.1,No,NaN
55022,PRD-0003,Storage Box Set,Home,Decor,Adidas,4.3,1784,737,77.5,Yes,NaN
277145,PRD-0006,Fitness Smart Band,Health,Personal Care,HP,4.7,4552,615,49.3,Yes,Better Price Elsewhere
622329,PRD-0008,Storage Box Set,Home,Kitchen,Nikon,3.1,711,277,16.1,No,NaN
538839,PRD-0008,USB Hub 7-Port,Electronics,Tablets,Sony,3.6,4522,359,61.1,No,NaN
267173,PRD-0008,Foam Roller,Health,Supplements,Lenovo,4.2,4163,962,35.7,Yes,NaN
955210,PRD-0009,Swimming Goggles,Sports,Outdoor,Apple,4.8,3773,11,22.4,Yes,NaN
301222,PRD-0009,Bedsheet Set Cotton,Home,Furniture,Fitbit,3.3,2708,0,27.3,Yes,NaN
25519,PRD-000D,Jump Rope Speed,Sports,Sports Wear,JBL,4.9,4884,222,77.9,No,NaN
222620,PRD-000D,Wireless Mouse 2.4GHz,Electronics,Smartphones,Xiaomi,3.1,4284,645,65.6,No,NaN
909872,PRD-000E,Casual Sneakers,Clothing,Mens Wear,Dell,3.0,1397,525,55.5,Yes,NaN
587043,PRD-000F,Massage Gun Deep Tissue,Health,Supplements,Sony,3.8,1043,725,76.7,No,NaN
242922,PRD-000F,Desk Lamp LED,Home,Furniture,Adidas,3.0,204,147,42.6,No,NaN
13520,PRD-000F,Fitness Smart Band,Health,Fitness,Nikon,4.0,2248,133,34.9,No,NaN
551452,PRD-000H,Running Shoes Air Zoom,Clothing,Mens Wear,Adidas,4.2,698,598,61.5,Yes,NaN
642349,PRD-000K,Fitness Smart Band,Health,Supplements,Philips,4.5,2013,48,32.4,Yes,NaN
74771,PRD-000K,Vacuum Robot Cleaner,Home,Appliances,Sony,3.6,1727,461,75.5,No,NaN

### need to change the product_id of the duplicates in the new_df (ending with _int)

In [21]:
new_df.columns

Index(['product_id', 'product_name', 'category', 'sub_category', 'brand',
       'product_rating_avg', 'product_reviews_count', 'stock_quantity',
       'fraud_risk_score', 'support_ticket_created', 'return_reason'],
      dtype='object')

In [22]:
new_df[["product_rating_avg","product_reviews_count","stock_quantity"]].sort_values("product_rating_avg", ascending = False)

        product_rating_avg  product_reviews_count  stock_quantity
215664                 5.0                   1966             927
981878                 5.0                   1776              71
779647                 5.0                   1259              66
61494                  5.0                   2762             450
386466                 5.0                   3158             172
...                    ...                    ...             ...
495526                 3.0                   3895             900
310741                 3.0                   4305             719
157159                 3.0                   1841             458
157177                 3.0                    832             795
946960                 3.0                   1674             607

[1000123 rows x 3 columns]

### Data with needed columns

In [23]:
df_final = df[['order_id', 'order_date',  'order_year', 'order_month', 'order_day',
       'order_hour', 'order_minute', 'order_second','is_weekend',
       'order_status', 'customer_id', 'customer_name',
       'gender', 'age', 'customer_segment', 'country', 'city',
       'customer_loyalty_score', 'total_orders_by_customer',
       'account_creation_date', 'product_id', 'product_name', 'category',
       'sub_category', 'brand', 'product_rating_avg', 'product_reviews_count',
       'stock_quantity', 'unit_price_usd', 'quantity', 'discount_percent',
        'total_price_usd', 'cost_usd', 'profit_usd',
       'tax_usd', 'payment_method', 'payment_status',
       'installment_plan', 'shipping_method', 'shipping_cost_usd',
       'delivery_days', 'shipping_country', 'warehouse_location',
       'delivery_status', 'device_type'
        ]]

In [24]:
df_final.isna().sum()

order_id                    0
order_date                  0
order_year                  0
order_month                 0
order_day                   0
order_hour                  0
order_minute                0
order_second                0
is_weekend                  0
order_status                0
customer_id                 0
customer_name               0
gender                      0
age                         0
customer_segment            0
country                     0
city                        0
customer_loyalty_score      0
total_orders_by_customer    0
account_creation_date       0
product_id                  0
product_name                0
category                    0
sub_category                0
brand                       0
product_rating_avg          0
product_reviews_count       0
stock_quantity              0
unit_price_usd              0
quantity                    0
discount_percent            0
total_price_usd             0
cost_usd                    0
profit_usd                  0
tax_usd                     0
payment_method              0
payment_status              0
installment_plan            0
shipping_method             0
shipping_cost_usd           0
delivery_days               0
shipping_country            0
warehouse_location          0
delivery_status             0
device_type                 0
dtype: int64

In [25]:
df_final['product_id'] = pd.factorize(df_final['product_name'])[0] + 1

C:\Users\SWARNAVA KUNDU\AppData\Local\Temp\ipykernel_21528\3850374915.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final['product_id'] = pd.factorize(df_final['product_name'])[0] + 1

In [26]:
df_final["customer_id"] = df_final['customer_id'].astype(str) + '' + df_final.groupby('customer_id')['customer_name'].transform(lambda x: pd.factorize(x)[0]).astype(str)

C:\Users\SWARNAVA KUNDU\AppData\Local\Temp\ipykernel_21528\1064608495.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final["customer_id"] = df_final['customer_id'].astype(str) + '' + df_final.groupby('customer_id')['customer_name'].transform(lambda x: pd.factorize(x)[0]).astype(str)

In [27]:
df_final['order_id'] = df_final['order_id'].astype(str) + '' + df_final.groupby('order_id').cumcount().astype(str)

C:\Users\SWARNAVA KUNDU\AppData\Local\Temp\ipykernel_21528\3732978593.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final['order_id'] = df_final['order_id'].astype(str) + '' + df_final.groupby('order_id').cumcount().astype(str)

In [28]:
t1 = df_final.groupby('customer_id')["customer_name"].nunique().loc[lambda x : x>1]
t1

Series([], Name: customer_name, dtype: int64)

In [29]:
df_final["order_id"].nunique()-len(df)

0

In [30]:
df_final.shape

(1000123, 45)

## Removing Descrepensies

### customer id discrepancy

In [36]:
cols = [
    'customer_name',
    'gender',
    'age',
    'country',
    'city',
    'account_creation_date'
]

for customer_id, group in df_final.groupby('customer_id'):
    
    inconsistent_cols = []
    
    for col in cols:
        if group[col].nunique(dropna=False) > 1:
            inconsistent_cols.append(col)
    
    if inconsistent_cols:
        print(f"\nCustomer ID: {customer_id}")
        print("Inconsistent columns:", inconsistent_cols)
        
        for col in inconsistent_cols:
            print(f"{col}: {group[col].unique()}")

Customer ID: CUS-O97X40
Inconsistent columns: ['age', 'city', 'account_creation_date']
age: [50 24]
city: ['Lyon' 'Nice']
account_creation_date: ['2024-12-05' '2023-07-20']

In [31]:
cols = [
    'customer_name',
    'gender',
    'age',
    'country',
    'city',
    'account_creation_date'
]

check = df_final.groupby('customer_id')[cols].nunique(dropna=False)

bad_ids = check[(check > 1).any(axis=1)].index

print(bad_ids)

Index(['CUS-O97X40'], dtype='object', name='customer_id')

In [34]:
df_final.loc[
    df_final['customer_id'].isin(bad_ids),
    [
        'customer_id',
        'customer_name',
        'gender',
        'age',
        'country',
        'city',
        'account_creation_date',
        'order_id',
        'order_date'
    ]
]

,customer_id,customer_name,gender,age,country,city,account_creation_date,order_id,order_date
358556,CUS-O97X40,Christina Moore,Female,50,France,Lyon,2024-12-05,ORD-DB8P10,2025-11-05 00:49:50.341831
931891,CUS-O97X40,Christina Moore,Female,24,France,Nice,2023-07-20,ORD-W8HC70,2024-10-07 14:01:08.804220

In [35]:
df_final = df_final.drop(index = 358556)
df1 = df_final.copy()

### product mapping

In [36]:
home=['Kitchen', 'Furniture', 'Appliances', 'Bedding', 'Decor']
health= ['Supplements', 'Personal Care', 'Medical Devices']
sports= ['Gym Equipment', 'Fitness', 'Outdoor', 'Sports Wear']
Electronics= ['Cameras', 'Smartphones', 'Tablets', 'Laptops', 'Audio']
Clothing= ['Womens Wear', 'Mens Wear', 'Kids Wear', 'Shoes', 'Accessories']

In [37]:
print(len(df1[(df1['category'] == "Home") & (df1['sub_category'].isin(home))]))
print(len(df1[(df1['category'] == "Home") & (~df1['sub_category'].isin(home))]))


len(df1[(df1['category'] == "Home")])

200589
0

200589

In [38]:
cat = ['Home', 'Health', 'Sports', 'Electronics', 'Clothing']

sub_cat = {
    'Home': home,
    'Health': health,
    'Sports': sports,
    'Electronics': Electronics,
    'Clothing': Clothing
}

for i in cat:
    
    wrong = df1[
        (df1['category'] == i) &
        (~df1['sub_category'].isin(sub_cat[i]))
    ]
    
    print(i, "discrepancies:", len(wrong))
    print(wrong['sub_category'].value_counts())
    print()

Home discrepancies: 0
Series([], Name: count, dtype: int64)

Health discrepancies: 49567
sub_category
Fitness    49567
Name: count, dtype: int64

Sports discrepancies: 50483
sub_category
Accessories    50483
Name: count, dtype: int64

Electronics discrepancies: 33294
sub_category
Accessories    33294
Name: count, dtype: int64

Clothing discrepancies: 0
Series([], Name: count, dtype: int64)

In [39]:
cat = ['Home', 'Health', 'Sports', 'Electronics', 'Clothing']

sub_cat = {
    'Home': home,
    'Health': health,
    'Sports': sports,
    'Electronics': Electronics,
    'Clothing': Clothing
}

for i in cat:
    
    valid = len(df1[
        (df1['category'] == i) &
        (df1['sub_category'].isin(sub_cat[i]))
    ])
    
    invalid = len(df1[
        (df1['category'] == i) &
        (~df1['sub_category'].isin(sub_cat[i]))
    ])
    
    total = len(df1[df1['category'] == i])
    
    print(i)
    print("Valid:", valid)
    print("Invalid:", invalid)
    print("Total:", total)
    print()

Home
Valid: 200589
Invalid: 0
Total: 200589

Health
Valid: 150007
Invalid: 49567
Total: 199574

Sports
Valid: 149914
Invalid: 50483
Total: 200397

Electronics
Valid: 166725
Invalid: 33294
Total: 200019

Clothing
Valid: 199543
Invalid: 0
Total: 199543

In [40]:
for i in cat:
    
    wrong = df1[
        (df1['category'] == i) &
        (~df1['sub_category'].isin(sub_cat[i]))
    ]
    
    print("\n", i)
    print(wrong[['category', 'sub_category']])

 Home
Empty DataFrame
Columns: [category, sub_category]
Index: []

 Health
        category sub_category
23        Health      Fitness
36        Health      Fitness
70        Health      Fitness
106       Health      Fitness
129       Health      Fitness
...          ...          ...
1000046   Health      Fitness
1000048   Health      Fitness
1000053   Health      Fitness
1000061   Health      Fitness
1000120   Health      Fitness

[49567 rows x 2 columns]

 Sports
        category sub_category
3         Sports  Accessories
126       Sports  Accessories
128       Sports  Accessories
170       Sports  Accessories
250       Sports  Accessories
...          ...          ...
1000091   Sports  Accessories
1000100   Sports  Accessories
1000105   Sports  Accessories
1000108   Sports  Accessories
1000118   Sports  Accessories

[50483 rows x 2 columns]

 Electronics
            category sub_category
50       Electronics  Accessories
140      Electronics  Accessories
149      Electronics  Accessories
168      Electronics  Accessories
277      Electronics  Accessories
...              ...          ...
999925   Electronics  Accessories
999932   Electronics  Accessories
999960   Electronics  Accessories
1000006  Electronics  Accessories
1000022  Electronics  Accessories

[33294 rows x 2 columns]

 Clothing
Empty DataFrame
Columns: [category, sub_category]
Index: []

In [41]:
for i in cat:
    
    wrong = df1[
        (df1['category'] == i) &
        (~df1['sub_category'].isin(sub_cat[i]))
    ]
    
    print("\n", i)
    print(wrong['sub_category'].value_counts())

 Home
Series([], Name: count, dtype: int64)

 Health
sub_category
Fitness    49567
Name: count, dtype: int64

 Sports
sub_category
Accessories    50483
Name: count, dtype: int64

 Electronics
sub_category
Accessories    33294
Name: count, dtype: int64

 Clothing
Series([], Name: count, dtype: int64)

In [42]:
for i in cat:
    
    wrong = df1[
        (df1['category'] == i) &
        (~df1['sub_category'].isin(sub_cat[i]))
    ]
    
    print("\n", i)
    display(wrong)

 Home

Empty DataFrame
Columns: [order_id, order_date, order_year, order_month, order_day, order_hour, order_minute, order_second, is_weekend, order_status, customer_id, customer_name, gender, age, customer_segment, country, city, customer_loyalty_score, total_orders_by_customer, account_creation_date, product_id, product_name, category, sub_category, brand, product_rating_avg, product_reviews_count, stock_quantity, unit_price_usd, quantity, discount_percent, total_price_usd, cost_usd, profit_usd, tax_usd, payment_method, payment_status, installment_plan, shipping_method, shipping_cost_usd, delivery_days, shipping_country, warehouse_location, delivery_status, device_type]
Index: []

[0 rows x 45 columns]

 Health

,order_id,order_date,order_year,order_month,order_day,order_hour,order_minute,order_second,is_weekend,order_status,...,payment_method,payment_status,installment_plan,shipping_method,shipping_cost_usd,delivery_days,shipping_country,warehouse_location,delivery_status,device_type
23,ORD-MDYVS0,2024-10-28 22:51:38.557816,2024,10,28,22,51,38,No,Completed,...,Bank Transfer,Paid,No,Next Day,2.88,1,Australia,EU-Central,Delivered,Desktop
36,ORD-EWVIY0,2024-10-07 16:38:12.614625,2024,10,7,16,38,12,No,Completed,...,Bank Transfer,Paid,Yes,Express,23.42,14,Canada,EU-Central,In Transit,Tablet
70,ORD-A5S000,2024-12-29 11:31:00.469026,2024,12,29,11,31,0,Yes,Completed,...,Apple Pay,Paid,No,Economy,10.08,4,Italy,USA-East,Delivered,Tablet
106,ORD-YV3LX0,2025-03-27 01:46:06.253117,2025,3,27,1,46,6,No,Completed,...,Debit Card,Paid,No,Next Day,22.53,1,Netherlands,USA-East,Delivered,Mobile
129,ORD-B2JTX0,2024-06-21 23:03:05.972731,2024,6,21,23,3,5,No,Completed,...,PayPal,Paid,Yes,Express,3.61,3,Spain,USA-West,Failed,Mobile
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000046,ORD-JGAPJ0,2025-10-06 07:28:27.958109,2025,10,6,7,28,27,No,Returned,...,Bank Transfer,Paid,No,Standard,22.93,14,Canada,USA-East,Failed,Desktop
1000048,ORD-KKHBG0,2025-09-01 16:08:51.336731,2025,9,1,16,8,51,No,Completed,...,PayPal,Paid,No,Economy,21.30,14,Germany,USA-East,Failed,Mobile
1000053,ORD-44NYT0,2025-02-26 23:28:50.131622,2025,2,26,23,28,50,No,Completed,...,Debit Card,Paid,Yes,Standard,18.13,10,France,USA-East,Delivered,Mobile
1000061,ORD-QQS0G0,2025-11-03 14:37:52.614143,2025,11,3,14,37,52,No,Completed,...,Apple Pay,Paid,Yes,Next Day,19.35,14,Spain,Asia-Pacific,Delivered,Desktop
1000120,ORD-O2H6B0,2024-11-09 21:15:09.983331,2024,11,9,21,15,9,Yes,Completed,...,Credit Card,Paid,No,Economy,17.02,2,Spain,EU-Central,Delivered,Desktop

 Sports

,order_id,order_date,order_year,order_month,order_day,order_hour,order_minute,order_second,is_weekend,order_status,...,payment_method,payment_status,installment_plan,shipping_method,shipping_cost_usd,delivery_days,shipping_country,warehouse_location,delivery_status,device_type
3,ORD-EIMVI0,2024-09-27 06:24:44.913768,2024,9,27,6,24,44,No,Completed,...,Credit Card,Paid,No,Express,4.76,8,Italy,USA-West,Delivered,Mobile
126,ORD-Q4PBG0,2025-09-24 07:23:01.494564,2025,9,24,7,23,1,No,Completed,...,Debit Card,Paid,Yes,Standard,19.13,11,Belgium,EU-Central,Delivered,Desktop
128,ORD-SKXLO0,2026-01-12 22:12:53.012619,2026,1,12,22,12,53,No,Completed,...,Bank Transfer,Paid,Yes,Next Day,16.15,5,Italy,UK,Delivered,Desktop
170,ORD-YOLD60,2026-01-14 05:17:12.560864,2026,1,14,5,17,12,No,Pending,...,Apple Pay,Failed,Yes,Economy,14.81,5,United Kingdom,USA-East,Delivered,Tablet
250,ORD-6UZS10,2025-08-13 15:29:17.031274,2025,8,13,15,29,17,No,Completed,...,Debit Card,Paid,No,Standard,1.18,5,Italy,Asia-Pacific,Delivered,Tablet
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000091,ORD-VHEDV0,2024-11-05 12:05:32.528072,2024,11,5,12,5,32,No,Processing,...,Apple Pay,Paid,No,Express,8.13,13,Italy,EU-Central,Delivered,Mobile
1000100,ORD-AKRGX0,2024-03-03 04:27:40.071003,2024,3,3,4,27,40,Yes,Completed,...,Bank Transfer,Paid,No,Economy,24.36,12,United States,Asia-Pacific,In Transit,Tablet
1000105,ORD-CHTXM0,2024-08-28 04:42:15.554907,2024,8,28,4,42,15,No,Completed,...,Credit Card,Paid,No,Standard,21.07,13,Belgium,USA-East,Failed,Desktop
1000108,ORD-QEFYU0,2025-04-23 13:52:43.847353,2025,4,23,13,52,43,No,Completed,...,Debit Card,Paid,No,Next Day,2.96,13,United States,USA-West,In Transit,Mobile
1000118,ORD-MH6TM0,2024-08-21 19:30:06.902744,2024,8,21,19,30,6,No,Completed,...,Bank Transfer,Paid,Yes,Standard,15.43,14,Australia,EU-Central,Delivered,Mobile

 Electronics

,order_id,order_date,order_year,order_month,order_day,order_hour,order_minute,order_second,is_weekend,order_status,...,payment_method,payment_status,installment_plan,shipping_method,shipping_cost_usd,delivery_days,shipping_country,warehouse_location,delivery_status,device_type
50,ORD-E1OCJ0,2025-03-10 05:16:36.302780,2025,3,10,5,16,36,No,Completed,...,Bank Transfer,Paid,No,Economy,6.71,14,France,EU-Central,Delivered,Tablet
140,ORD-KGJZO0,2024-10-20 22:19:15.778872,2024,10,20,22,19,15,Yes,Completed,...,Credit Card,Paid,No,Next Day,10.48,11,Italy,UK,In Transit,Tablet
149,ORD-CYUKN0,2024-11-04 21:56:34.400085,2024,11,4,21,56,34,No,Completed,...,Bank Transfer,Paid,No,Express,3.44,1,Belgium,USA-East,Delivered,Tablet
168,ORD-AUUJ00,2025-08-02 15:15:49.839181,2025,8,2,15,15,49,Yes,Pending,...,Apple Pay,Pending,Yes,Standard,0.98,10,Netherlands,USA-West,Delivered,Mobile
277,ORD-UMAPQ0,2025-09-22 01:26:44.998697,2025,9,22,1,26,44,No,Completed,...,Debit Card,Paid,No,Express,10.24,3,Belgium,UK,Delivered,Mobile
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999925,ORD-YCSRT0,2025-01-17 21:13:08.898993,2025,1,17,21,13,8,No,Returned,...,Apple Pay,Paid,No,Express,16.20,2,United Kingdom,EU-Central,Delivered,Tablet
999932,ORD-LQP120,2025-01-13 07:59:14.941854,2025,1,13,7,59,14,No,Completed,...,Credit Card,Paid,No,Economy,7.51,4,Canada,EU-Central,In Transit,Tablet
999960,ORD-K84RS0,2024-02-04 15:32:47.766222,2024,2,4,15,32,47,Yes,Completed,...,Bank Transfer,Paid,Yes,Express,4.29,1,Germany,Asia-Pacific,Delivered,Tablet
1000006,ORD-51PFT0,2024-04-08 10:25:31.991615,2024,4,8,10,25,31,No,Returned,...,PayPal,Paid,No,Standard,6.78,1,Netherlands,USA-West,In Transit,Mobile
1000022,ORD-VPE390,2025-09-12 23:18:02.050885,2025,9,12,23,18,2,No,Pending,...,Apple Pay,Failed,No,Express,17.07,12,Germany,USA-East,Delivered,Desktop

 Clothing

Empty DataFrame
Columns: [order_id, order_date, order_year, order_month, order_day, order_hour, order_minute, order_second, is_weekend, order_status, customer_id, customer_name, gender, age, customer_segment, country, city, customer_loyalty_score, total_orders_by_customer, account_creation_date, product_id, product_name, category, sub_category, brand, product_rating_avg, product_reviews_count, stock_quantity, unit_price_usd, quantity, discount_percent, total_price_usd, cost_usd, profit_usd, tax_usd, payment_method, payment_status, installment_plan, shipping_method, shipping_cost_usd, delivery_days, shipping_country, warehouse_location, delivery_status, device_type]
Index: []

[0 rows x 45 columns]

In [43]:
df2 = df1[['shipping_method', 'shipping_cost_usd',
       'delivery_days', 'shipping_country', 'warehouse_location',
       'delivery_status']]
df2.head()
cat = ['Home', 'Health', 'Sports', 'Electronics', 'Clothing']

sub_cat = {
    'Home': home,
    'Health': health,
    'Sports': sports,
    'Electronics': Electronics,
    'Clothing': Clothing
}

discrepancies = []

for i in cat:
    wrong = df1[
        (df1['category'] == i) &
        (~df1['sub_category'].isin(sub_cat[i]))
    ]
    
    discrepancies.append(wrong)

discrepancies = pd.concat(discrepancies)

print(len(discrepancies))
print(len(df1))
(1-((len(df1)-len(discrepancies))/len(df1)))*100

133344
1000122

13.332773401645003

In [44]:
product_mapping = {
    # Home
    'Coffee Maker Automatic': ('Home', 'Appliances'),
    'Blender 1000W': ('Home', 'Appliances'),
    'Air Fryer 5L': ('Home', 'Appliances'),
    'Storage Box Set': ('Home', 'Furniture'),
    'Vacuum Robot Cleaner': ('Home', 'Appliances'),
    'Bedsheet Set Cotton': ('Home', 'Bedding'),
    'LED Strip Lights 5m': ('Home', 'Decor'),
    'Desk Lamp LED': ('Home', 'Decor'),

    # Health
    'Electric Toothbrush': ('Health', 'Personal Care'),
    'Massage Gun Deep Tissue': ('Health', 'Personal Care'),
    'Digital Blood Pressure Monitor': ('Health', 'Medical Devices'),
    'Digital Thermometer': ('Health', 'Medical Devices'),
    'Vitamin C Tablets': ('Health', 'Supplements'),

    # Sports
    'Yoga Mat Non-Slip': ('Sports', 'Fitness'),
    'Badminton Racket': ('Sports', 'Outdoor'),
    'Treadmill Folding': ('Sports', 'Gym Equipment'),
    'Sports Bra High Impact': ('Sports', 'Sports Wear'),
    'Swimming Goggles': ('Sports', 'Sports Wear'),
    'Resistance Bands Set': ('Sports', 'Gym Equipment'),
    'Foam Roller': ('Sports', 'Fitness'),
    'Tennis Balls Pack': ('Sports', 'Outdoor'),
    'Protein Shaker Bottle': ('Sports', 'Fitness'),
    'Jump Rope Speed': ('Sports', 'Fitness'),
    'Exercise Ball': ('Sports', 'Gym Equipment'),
    'Water Bottle Insulated': ('Sports', 'Outdoor'),
    'Dumbbells Set Adjustable': ('Sports', 'Gym Equipment'),
    'Fitness Smart Band': ('Sports', 'Fitness'),
    'Gym Gloves': ('Sports', 'Sports Wear'),

    # Electronics
    'Screen Protector Tempered Glass': ('Electronics', 'Smartphones'),
    'Phone Case Shockproof': ('Electronics', 'Smartphones'),
    'Wireless Mouse 2.4GHz': ('Electronics', 'Laptops'),
    'USB-C Fast Charger 65W': ('Electronics', 'Laptops'),
    '4K Webcam Pro': ('Electronics', 'Cameras'),
    'Wireless Bluetooth Earbuds': ('Electronics', 'Audio'),
    'USB Hub 7-Port': ('Electronics', 'Laptops'),
    'Portable SSD 1TB': ('Electronics', 'Laptops'),
    'Smart Watch Series 8': ('Electronics', 'Smartphones'),
    'Gaming Mechanical Keyboard RGB': ('Electronics', 'Laptops'),
    'Power Bank 20000mAh': ('Electronics', 'Smartphones'),

    # Clothing
    'Denim Jeans Slim Fit': ('Clothing', 'Mens Wear'),
    'Winter Jacket Waterproof': ('Clothing', 'Mens Wear'),
    'Running Shoes Air Zoom': ('Clothing', 'Shoes'),
    'Yoga Pants Leggings': ('Clothing', 'Womens Wear'),
    'Hooded Sweatshirt': ('Clothing', 'Mens Wear'),
    'Baseball Cap': ('Clothing', 'Accessories'),
    'Laptop Backpack Waterproof': ('Clothing', 'Accessories'),
    'Cotton T-Shirt Pack': ('Clothing', 'Mens Wear'),
    'Casual Sneakers': ('Clothing', 'Shoes')
}

In [45]:
for product, (category, subcategory) in product_mapping.items():
    df1.loc[df1['product_name'] == product, 'category'] = category
    df1.loc[df1['product_name'] == product, 'sub_category'] = subcategory

In [46]:
cat = ['Home', 'Health', 'Sports', 'Electronics', 'Clothing']

sub_cat = {
    'Home': home,
    'Health': health,
    'Sports': sports,
    'Electronics': Electronics,
    'Clothing': Clothing
}

discrepancies = []

for i in cat:
    wrong = df1[
        (df1['category'] == i) &
        (~df1['sub_category'].isin(sub_cat[i]))
    ]
    
    discrepancies.append(wrong)

discrepancies = pd.concat(discrepancies)

print(len(discrepancies))
print(len(df1))
(1-((len(df1)-len(discrepancies))/len(df1)))*100

0
1000122

0.0

### city, country, warehouse location discrepancy

In [47]:
city_to_country = {
    # Netherlands
    'Utrecht': 'Netherlands',
    'Amsterdam': 'Netherlands',
    'The Hague': 'Netherlands',
    'Eindhoven': 'Netherlands',
    'Rotterdam': 'Netherlands',

    # United States
    'Los Angeles': 'United States',
    'Phoenix': 'United States',
    'Houston': 'United States',
    'New York': 'United States',
    'Chicago': 'United States',

    # France
    'Nice': 'France',
    'Paris': 'France',
    'Lyon': 'France',
    'Toulouse': 'France',
    'Marseille': 'France',

    # Italy
    'Milan': 'Italy',
    'Turin': 'Italy',
    'Naples': 'Italy',
    'Florence': 'Italy',
    'Rome': 'Italy',

    # Germany
    'Berlin': 'Germany',
    'Frankfurt': 'Germany',
    'Munich': 'Germany',
    'Hamburg': 'Germany',
    'Cologne': 'Germany',

    # Canada
    'Calgary': 'Canada',
    'Toronto': 'Canada',
    'Vancouver': 'Canada',
    'Montreal': 'Canada',
    'Ottawa': 'Canada',

    # Australia
    'Adelaide': 'Australia',
    'Melbourne': 'Australia',
    'Sydney': 'Australia',
    'Brisbane': 'Australia',
    'Perth': 'Australia',

    # Belgium
    'Bruges': 'Belgium',
    'Ghent': 'Belgium',
    'Antwerp': 'Belgium',
    'Brussels': 'Belgium',
    'Liege': 'Belgium',

    # United Kingdom
    'London': 'United Kingdom',
    'Glasgow': 'United Kingdom',
    'Manchester': 'United Kingdom',
    'Birmingham': 'United Kingdom',
    'Leeds': 'United Kingdom',

    # Spain
    'Madrid': 'Spain',
    'Valencia': 'Spain',
    'Bilbao': 'Spain',
    'Seville': 'Spain',
    'Barcelona': 'Spain'
}

In [48]:
country_to_warehouse = {
    'United Kingdom': 'UK',
    'United States': 'USA-East',   
    'Australia': 'Asia-Pacific',
    'Netherlands': 'EU-Central',
    'France': 'EU-Central',
    'Italy': 'EU-Central',
    'Germany': 'EU-Central',
    'Belgium': 'EU-Central',
    'Spain': 'EU-Central',
    'Canada': 'USA-West'
}

In [49]:
df1['country'] = df1['city'].map(city_to_country)
df1['warehouse_location'] = df1['country'].map(country_to_warehouse)

In [50]:
unmapped_cities = df1.loc[
    ~df1['city'].isin(city_to_country.keys()),
    'city'
].unique()

print("Unmapped cities:")
print(unmapped_cities)

Unmapped cities:
[]

In [51]:
df1['expected_country'] = df1['city'].map(city_to_country)

country_errors = df1[
    df1['country'] != df1['expected_country']
]

print("Number of country discrepancies:", len(country_errors))

if len(country_errors) > 0:
    print(country_errors[['city', 'country', 'expected_country']])
else:
    print("No city-country discrepancies found.")

Number of country discrepancies: 0
No city-country discrepancies found.

### Creating new columns

In [52]:
warehouse_dict = {warehouse: i + 1 for i, warehouse in enumerate(sorted(df1['warehouse_location'].dropna().unique()))}
country_dict = {country: i + 1 for i, country in enumerate(sorted(df1['country'].dropna().unique()))}
city_dict = {city: i + 1 for i, city in enumerate(sorted(df1['city'].dropna().unique()))}

In [53]:
df1['warehouse_location_code'] = (df1['warehouse_location'].map(warehouse_dict))
df1['country_code'] = (df1['country'].map(country_dict))
df1['city_code'] = (df1['city'].map(city_dict))

In [54]:
df1['warehouse_id'] = (df1['warehouse_location_code'].astype(str)+ df1['country_code'].astype(str).str.zfill(2)+ df1['city_code'].astype(str).str.zfill(2))
df1.drop(columns=['warehouse_location_code','country_code','city_code','expected_country'],inplace=True)
df1['warehouse_id'] = df1['warehouse_id'].astype(int)

In [55]:
category_dict = {category: i + 1 for i, category in enumerate(sorted(df1['category'].dropna().unique()))}
subcategory_dict = {subcategory: i + 1 for i, subcategory in enumerate(sorted(df1['sub_category'].dropna().unique()))}

In [56]:
df1['category_code'] = (df1['category'].map(category_dict))
df1['subcategory_code'] = (df1['sub_category'].map(subcategory_dict))

In [57]:
df1['inventory_id'] = (df1['category_code'].astype(str).str.zfill(2)+ df1['subcategory_code'].astype(str).str.zfill(2))
df1['inventory_id']=df1['inventory_id'].astype(int)
df1.drop(columns=['category_code','subcategory_code'],inplace=True)

In [58]:
df1['order_date'] = pd.to_datetime(
    df1[['order_year', 'order_month', 'order_day']].rename(
        columns={
            'order_year': 'year',
            'order_month': 'month',
            'order_day': 'day'
        }
    )
)

In [61]:
# Dropping Brand column
df1 = df1.drop('brand', axis = 1)

In [63]:
df_final = df1.copy()

In [64]:
df_final.columns

Index(['order_id', 'order_date', 'order_year', 'order_month', 'order_day',
       'order_hour', 'order_minute', 'order_second', 'is_weekend',
       'order_status', 'customer_id', 'customer_name', 'gender', 'age',
       'customer_segment', 'country', 'city', 'customer_loyalty_score',
       'total_orders_by_customer', 'account_creation_date', 'product_id',
       'product_name', 'category', 'sub_category', 'product_rating_avg',
       'product_reviews_count', 'stock_quantity', 'unit_price_usd', 'quantity',
       'discount_percent', 'total_price_usd', 'cost_usd', 'profit_usd',
       'tax_usd', 'payment_method', 'payment_status', 'installment_plan',
       'shipping_method', 'shipping_cost_usd', 'delivery_days',
       'shipping_country', 'warehouse_location', 'delivery_status',
       'device_type', 'warehouse_id', 'inventory_id'],
      dtype='object')

## final data

In [65]:
save_dir = os.path.join("data", "cleaned")
new_path = os.path.join(save_dir, "final_dataset.csv")
os.makedirs(save_dir, exist_ok=True)
# Save the dataset
df_final.to_csv(new_path, index=False)