In [2]:
import os
import pandas as pd
import numpy as np

In [3]:
path = os.path.join("data", "ecommerce_dataset_+1m.csv")
df=pd.read_csv(path)

In [4]:
df

,order_id,order_date,order_year,order_month,order_day,order_hour,order_minute,order_second,is_weekend,order_status,...,campaign_source,device_type,traffic_source,session_duration_minutes,pages_visited,abandoned_cart_before,fraud_risk_score,profit_margin_percent,order_priority,support_ticket_created
0,ORD-XAJI0,2024-10-14 11:20:05.496679,2024,10,14,11,20,5,No,Completed,...,Email,Mobile,Search,52.1,13,No,45.3,28.66,Medium,Yes
1,ORD-NHJ7X,2024-10-21 00:49:44.681065,2024,10,21,0,49,44,No,Completed,...,Google Ads,Desktop,Referral,36.2,15,No,97.1,33.91,Low,Yes
2,ORD-YTJXE,2025-03-17 19:49:36.983317,2025,3,17,19,49,36,No,Completed,...,Facebook,Tablet,Search,43.1,13,No,43.8,52.77,High,No
3,ORD-EIMVI,2024-09-27 06:24:44.913768,2024,9,27,6,24,44,No,Completed,...,Instagram,Mobile,Direct,39.5,18,Yes,96.9,38.15,Low,Yes
4,ORD-OR56F,2025-05-21 17:10:48.401882,2025,5,21,17,10,48,No,Completed,...,Facebook,Tablet,Social,28.0,3,Yes,45.8,33.05,High,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000118,ORD-MH6TM,2024-08-21 19:30:06.902744,2024,8,21,19,30,6,No,Completed,...,Affiliate,Mobile,Search,13.6,1,Yes,99.8,45.23,High,Yes
1000119,ORD-ILXX0,2024-04-05 09:58:34.625191,2024,4,5,9,58,34,No,Cancelled,...,Google Ads,Tablet,Email,30.2,13,No,36.7,49.46,Low,Yes
1000120,ORD-O2H6B,2024-11-09 21:15:09.983331,2024,11,9,21,15,9,Yes,Completed,...,Google Ads,Desktop,Direct,43.4,1,No,51.2,45.83,High,Yes
1000121,ORD-EGD60,2025-10-17 12:48:19.451188,2025,10,17,12,48,19,No,Completed,...,Facebook,Mobile,Email,30.7,9,No,72.4,41.07,High,Yes
1000122,ORD-HBJAD,2025-04-17 15:30:36.405483,2025,4,17,15,30,36,No,Completed,...,Facebook,Desktop,Search,43.2,4,Yes,25.9,42.64,Low,Yes

In [5]:
df.describe()

,order_year,order_month,order_day,order_hour,order_minute,order_second,age,customer_loyalty_score,total_orders_by_customer,product_rating_avg,...,cost_usd,profit_usd,tax_usd,shipping_cost_usd,delivery_days,rating,session_duration_minutes,pages_visited,fraud_risk_score,profit_margin_percent
count,1.000123e+06,1.000123e+06,1.000123e+06,1.000123e+06,1.000123e+06,1.000123e+06,1.000123e+06,1.000123e+06,1.000123e+06,1.000123e+06,...,1.000123e+06,1.000123e+06,1.000123e+06,1.000123e+06,1.000123e+06,1.000123e+06,1.000123e+06,1.000123e+06,1.000123e+06,1.000123e+06
mean,2.024590e+03,6.514849e+00,1.575253e+01,1.148814e+01,2.949467e+01,2.948548e+01,4.649414e+01,4.997252e+01,2.548700e+01,3.999194e+00,...,2.423092e+02,1.609270e+02,3.025157e+01,1.250445e+01,7.506648e+00,2.999784e+00,3.051033e+01,1.050609e+01,4.996161e+01,3.946517e+01
std,5.758891e-01,3.448711e+00,8.799790e+00,6.918078e+00,1.730984e+01,1.732781e+01,1.673373e+01,2.889377e+01,1.443421e+01,5.784694e-01,...,2.267157e+02,1.619301e+02,2.889152e+01,7.216416e+00,4.032930e+00,1.414973e+00,1.703368e+01,5.766207e+00,2.884771e+01,1.094131e+01
min,2.024000e+03,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.800000e+01,0.000000e+00,1.000000e+00,3.000000e+00,...,4.030000e+00,7.000000e-01,4.300000e-01,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,6.660000e+00
25%,2.024000e+03,4.000000e+00,8.000000e+00,5.000000e+00,1.400000e+01,1.400000e+01,3.200000e+01,2.490000e+01,1.300000e+01,3.500000e+00,...,8.245000e+01,5.069000e+01,1.012000e+01,6.260000e+00,4.000000e+00,2.000000e+00,1.570000e+01,6.000000e+00,2.500000e+01,3.169000e+01
50%,2.025000e+03,7.000000e+00,1.600000e+01,1.100000e+01,3.000000e+01,2.900000e+01,4.600000e+01,5.000000e+01,2.500000e+01,4.000000e+00,...,1.725300e+02,1.087900e+02,2.128000e+01,1.250000e+01,8.000000e+00,3.000000e+00,3.050000e+01,1.100000e+01,5.000000e+01,3.990000e+01
75%,2.025000e+03,1.000000e+01,2.300000e+01,1.700000e+01,4.400000e+01,4.400000e+01,6.100000e+01,7.500000e+01,3.800000e+01,4.500000e+00,...,3.264500e+02,2.146400e+02,4.059000e+01,1.874000e+01,1.100000e+01,4.000000e+00,4.530000e+01,1.600000e+01,7.490000e+01,4.817000e+01
max,2.026000e+03,1.200000e+01,3.100000e+01,2.300000e+01,5.900000e+01,5.900000e+01,7.500000e+01,1.000000e+02,5.000000e+01,5.000000e+00,...,1.743700e+03,1.495750e+03,2.455900e+02,2.500000e+01,1.400000e+01,5.000000e+00,6.000000e+01,2.000000e+01,1.000000e+02,6.002000e+01

In [6]:
for i in df.columns:
    if df[i].isnull().sum() >0:
        print(i,df[i].isnull().sum())

return_reason 900244
customer_feedback 199617
coupon_code 500083

In [7]:
df.columns

Index(['order_id', 'order_date', 'order_year', 'order_month', 'order_day',
       'order_hour', 'order_minute', 'order_second', 'is_weekend',
       'order_status', 'return_reason', 'customer_id', 'customer_name',
       'gender', 'age', 'customer_segment', 'country', 'city',
       'customer_loyalty_score', 'total_orders_by_customer',
       'account_creation_date', 'product_id', 'product_name', 'category',
       'sub_category', 'brand', 'product_rating_avg', 'product_reviews_count',
       'stock_quantity', 'unit_price_usd', 'quantity', 'discount_percent',
       'discount_amount_usd', 'total_price_usd', 'cost_usd', 'profit_usd',
       'tax_usd', 'currency', 'payment_method', 'payment_status',
       'installment_plan', 'shipping_method', 'shipping_cost_usd',
       'delivery_days', 'shipping_country', 'warehouse_location',
       'delivery_status', 'rating', 'review_sentiment', 'customer_feedback',
       'coupon_used', 'coupon_code', 'campaign_source', 'device_type',
       'traffic_source', 'session_duration_minutes', 'pages_visited',
       'abandoned_cart_before', 'fraud_risk_score', 'profit_margin_percent',
       'order_priority', 'support_ticket_created'],
      dtype='str')

In [8]:
cols_to_drop=['customer_id', 'customer_name', 'gender', 'age', 
    'customer_segment', 'country', 'city', 'customer_loyalty_score', 
    'total_orders_by_customer', 'account_creation_date','device_type', 'session_duration_minutes', 'pages_visited', 
    'abandoned_cart_before', 'traffic_source', 'campaign_source', 
    'fraud_risk_score','payment_method', 'payment_status', 'installment_plan', 
    'currency', 'tax_usd', 'coupon_code','rating', 'review_sentiment', 'customer_feedback', 
    'product_rating_avg', 'product_reviews_count', 'support_ticket_created','order_hour', 'order_minute', 'order_second','discount_amount_usd', 'total_price_usd', 'profit_usd', 
    'profit_margin_percent', 'coupon_used','product_name','order_year', 'order_month', 'order_day', 'is_weekend','shipping_cost_usd', 'shipping_country', 'delivery_status', 'order_priority']

In [9]:
df_clean=df.drop(columns=cols_to_drop)

In [10]:
df_clean

,order_id,order_date,order_status,return_reason,product_id,category,sub_category,brand,stock_quantity,unit_price_usd,quantity,discount_percent,cost_usd,shipping_method,delivery_days,warehouse_location
0,ORD-XAJI0,2024-10-14 11:20:05.496679,Completed,NaN,PRD-1FPK,Home,Kitchen,Nike,99,120.51,3,10,232.14,Economy,5,UK
1,ORD-NHJ7X,2024-10-21 00:49:44.681065,Completed,NaN,PRD-C6UZ,Health,Supplements,Asus,146,60.33,2,15,67.78,Next Day,3,UK
2,ORD-YTJXE,2025-03-17 19:49:36.983317,Completed,NaN,PRD-T2TA,Home,Furniture,Asus,899,295.89,3,0,419.22,Economy,13,UK
3,ORD-EIMVI,2024-09-27 06:24:44.913768,Completed,NaN,PRD-IROD,Sports,Accessories,Adidas,884,186.33,1,0,115.24,Express,8,USA-West
4,ORD-OR56F,2025-05-21 17:10:48.401882,Completed,NaN,PRD-LBR7,Electronics,Cameras,Anker,82,427.16,1,10,257.39,Standard,7,UK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000118,ORD-MH6TM,2024-08-21 19:30:06.902744,Completed,NaN,PRD-PHM3,Sports,Accessories,Dell,551,193.50,3,10,286.17,Standard,14,EU-Central
1000119,ORD-ILXX0,2024-04-05 09:58:34.625191,Cancelled,NaN,PRD-T0M6,Clothing,Shoes,GoPro,218,27.80,5,0,70.25,Express,3,EU-Central
1000120,ORD-O2H6B,2024-11-09 21:15:09.983331,Completed,NaN,PRD-OAN2,Health,Fitness,Logitech,1000,180.63,1,15,83.17,Economy,2,EU-Central
1000121,ORD-EGD60,2025-10-17 12:48:19.451188,Completed,NaN,PRD-71G1,Sports,Sports Wear,Samsung,303,33.92,3,0,59.97,Next Day,11,USA-East
1000122,ORD-HBJAD,2025-04-17 15:30:36.405483,Completed,NaN,PRD-NBP2,Clothing,Shoes,Asus,543,139.44,3,20,191.97,Next Day,10,USA-East

In [11]:
len(df_clean.columns)

16

In [12]:
df_clean.describe()

,stock_quantity,unit_price_usd,quantity,discount_percent,cost_usd,delivery_days
count,1.000123e+06,1.000123e+06,1.000123e+06,1.000123e+06,1.000123e+06,1.000123e+06
mean,4.998088e+02,1.470166e+02,2.997367e+00,8.500029e+00,2.423092e+02,7.506648e+00
std,2.888580e+02,1.036740e+02,1.414994e+00,7.595765e+00,2.267157e+02,4.032930e+00
min,0.000000e+00,1.000000e+01,1.000000e+00,0.000000e+00,4.030000e+00,1.000000e+00
25%,2.500000e+02,6.951000e+01,2.000000e+00,0.000000e+00,8.245000e+01,4.000000e+00
50%,5.000000e+02,1.251100e+02,3.000000e+00,1.000000e+01,1.725300e+02,8.000000e+00
75%,7.500000e+02,1.956100e+02,4.000000e+00,1.500000e+01,3.264500e+02,1.100000e+01
max,1.000000e+03,5.000000e+02,5.000000e+00,2.500000e+01,1.743700e+03,1.400000e+01