In [1]:
import pandas as pd
import os

In [2]:
path = os.path.join("data", "ecommerce_dataset_+1m.csv") 
df=pd.read_csv(path)

In [3]:
df.columns

Index(['order_id', 'order_date', 'order_year', 'order_month', 'order_day',
       'order_hour', 'order_minute', 'order_second', 'is_weekend',
       'order_status', 'return_reason', 'customer_id', 'customer_name',
       'gender', 'age', 'customer_segment', 'country', 'city',
       'customer_loyalty_score', 'total_orders_by_customer',
       'account_creation_date', 'product_id', 'product_name', 'category',
       'sub_category', 'brand', 'product_rating_avg', 'product_reviews_count',
       'stock_quantity', 'unit_price_usd', 'quantity', 'discount_percent',
       'discount_amount_usd', 'total_price_usd', 'cost_usd', 'profit_usd',
       'tax_usd', 'currency', 'payment_method', 'payment_status',
       'installment_plan', 'shipping_method', 'shipping_cost_usd',
       'delivery_days', 'shipping_country', 'warehouse_location',
       'delivery_status', 'rating', 'review_sentiment', 'customer_feedback',
       'coupon_used', 'coupon_code', 'campaign_source', 'device_type',
       'traffic_source', 'session_duration_minutes', 'pages_visited',
       'abandoned_cart_before', 'fraud_risk_score', 'profit_margin_percent',
       'order_priority', 'support_ticket_created'],
      dtype='object')

In [4]:
# created new_df with my cols

w_cols = [
    'product_id',
    'product_name',
    'category',
    'sub_category',
    'brand',
    'product_rating_avg',
    'product_reviews_count',
    'stock_quantity',
    'fraud_risk_score',
    'support_ticket_created',
    'return_reason'
]

new_df = df[w_cols].copy()

new_df.head()

,product_id,product_name,category,sub_category,brand,product_rating_avg,product_reviews_count,stock_quantity,fraud_risk_score,support_ticket_created,return_reason
0,PRD-1FPK,Coffee Maker Automatic,Home,Kitchen,Nike,3.2,3112,99,45.3,Yes,NaN
1,PRD-C6UZ,Yoga Mat Non-Slip,Health,Supplements,Asus,3.8,3758,146,97.1,Yes,NaN
2,PRD-T2TA,Blender 1000W,Home,Furniture,Asus,3.0,2973,899,43.8,No,NaN
3,PRD-IROD,Badminton Racket,Sports,Accessories,Adidas,3.8,3825,884,96.9,Yes,NaN
4,PRD-LBR7,Screen Protector Tempered Glass,Electronics,Cameras,Anker,3.1,4160,82,45.8,Yes,NaN

In [5]:
new_df.columns

Index(['product_id', 'product_name', 'category', 'sub_category', 'brand',
       'product_rating_avg', 'product_reviews_count', 'stock_quantity',
       'fraud_risk_score', 'support_ticket_created', 'return_reason'],
      dtype='object')

In [6]:
len(new_df.columns)

11

In [7]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000123 entries, 0 to 1000122
Data columns (total 11 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   product_id              1000123 non-null  object
 1   product_name            1000123 non-null  object
 2   category                1000123 non-null  object
 3   sub_category            1000123 non-null  object
 4   brand                   1000123 non-null  object
 5   product_rating_avg      1000123 non-null  float64
 6   product_reviews_count   1000123 non-null  int64
 7   stock_quantity          1000123 non-null  int64
 8   fraud_risk_score        1000123 non-null  float64
 9   support_ticket_created  1000123 non-null  object
 10  return_reason           99879 non-null    object
dtypes: float64(2), int64(2), object(7)
memory usage: 83.9+ MB

In [8]:
new_df.isnull().sum()

product_id                     0
product_name                   0
category                       0
sub_category                   0
brand                          0
product_rating_avg             0
product_reviews_count          0
stock_quantity                 0
fraud_risk_score               0
support_ticket_created         0
return_reason             900244
dtype: int64

In [9]:
new_df['category'].value_counts()

category
Home           200589
Sports         200397
Electronics    200019
Health         199574
Clothing       199544
Name: count, dtype: int64

In [10]:
new_df[['category','sub_category']].value_counts().sort_index()

category     sub_category
Clothing     Accessories        39925
             Kids Wear          39789
             Mens Wear          39909
             Shoes              40036
             Womens Wear        39885
Electronics  Accessories        33294
             Audio              33340
             Cameras            33515
             Laptops            33232
             Smartphones        33265
             Tablets            33373
Health       Fitness            49567
             Medical Devices    49826
             Personal Care      50039
             Supplements        50142
Home         Appliances         39588
             Bedding            40105
             Decor              40507
             Furniture          40147
             Kitchen            40242
Sports       Accessories        50483
             Gym Equipment      50141
             Outdoor            49816
             Sports Wear        49957
Name: count, dtype: int64

In [11]:
new_df['category'].isnull().sum()
new_df['sub_category'].isnull().sum()

0

In [12]:
new_df.columns

Index(['product_id', 'product_name', 'category', 'sub_category', 'brand',
       'product_rating_avg', 'product_reviews_count', 'stock_quantity',
       'fraud_risk_score', 'support_ticket_created', 'return_reason'],
      dtype='object')

In [13]:
new_df

,product_id,product_name,category,sub_category,brand,product_rating_avg,product_reviews_count,stock_quantity,fraud_risk_score,support_ticket_created,return_reason
0,PRD-1FPK,Coffee Maker Automatic,Home,Kitchen,Nike,3.2,3112,99,45.3,Yes,NaN
1,PRD-C6UZ,Yoga Mat Non-Slip,Health,Supplements,Asus,3.8,3758,146,97.1,Yes,NaN
2,PRD-T2TA,Blender 1000W,Home,Furniture,Asus,3.0,2973,899,43.8,No,NaN
3,PRD-IROD,Badminton Racket,Sports,Accessories,Adidas,3.8,3825,884,96.9,Yes,NaN
4,PRD-LBR7,Screen Protector Tempered Glass,Electronics,Cameras,Anker,3.1,4160,82,45.8,Yes,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1000118,PRD-PHM3,Jump Rope Speed,Sports,Accessories,Dell,3.3,1311,551,99.8,Yes,NaN
1000119,PRD-T0M6,Baseball Cap,Clothing,Shoes,GoPro,3.6,1849,218,36.7,Yes,NaN
1000120,PRD-OAN2,Digital Thermometer,Health,Fitness,Logitech,3.8,2030,1000,51.2,Yes,NaN
1000121,PRD-71G1,Badminton Racket,Sports,Sports Wear,Samsung,3.2,4015,303,72.4,Yes,NaN
1000122,PRD-NBP2,Hooded Sweatshirt,Clothing,Shoes,Asus,3.1,3941,543,25.9,Yes,NaN

In [14]:
new_df[['product_id','product_name']]

        product_id                     product_name
0         PRD-1FPK           Coffee Maker Automatic
1         PRD-C6UZ                Yoga Mat Non-Slip
2         PRD-T2TA                    Blender 1000W
3         PRD-IROD                 Badminton Racket
4         PRD-LBR7  Screen Protector Tempered Glass
...            ...                              ...
1000118   PRD-PHM3                  Jump Rope Speed
1000119   PRD-T0M6                     Baseball Cap
1000120   PRD-OAN2              Digital Thermometer
1000121   PRD-71G1                 Badminton Racket
1000122   PRD-NBP2                Hooded Sweatshirt

[1000123 rows x 2 columns]

In [15]:
len(new_df)

1000123

In [16]:
ids = new_df.groupby("product_id")["product_name"].nunique()
ids = ids[ids > 1].index

new_df[new_df["product_id"].isin(ids)]

,product_id,product_name,category,sub_category,brand,product_rating_avg,product_reviews_count,stock_quantity,fraud_risk_score,support_ticket_created,return_reason
1,PRD-C6UZ,Yoga Mat Non-Slip,Health,Supplements,Asus,3.8,3758,146,97.1,Yes,NaN
2,PRD-T2TA,Blender 1000W,Home,Furniture,Asus,3.0,2973,899,43.8,No,NaN
3,PRD-IROD,Badminton Racket,Sports,Accessories,Adidas,3.8,3825,884,96.9,Yes,NaN
10,PRD-UHZ1,Massage Gun Deep Tissue,Health,Personal Care,Nikon,4.2,938,796,85.0,Yes,NaN
12,PRD-93KM,Treadmill Folding,Sports,Sports Wear,Xiaomi,4.4,1036,280,15.2,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1000111,PRD-F435,Jump Rope Speed,Sports,Outdoor,Adidas,3.5,4413,932,69.8,Yes,Better Price Elsewhere
1000112,PRD-4T9C,Smart Watch Series 8,Electronics,Cameras,Philips,3.4,1623,318,39.4,Yes,NaN
1000116,PRD-C8TB,Tennis Balls Pack,Sports,Sports Wear,Xiaomi,4.9,1285,100,91.3,No,NaN
1000118,PRD-PHM3,Jump Rope Speed,Sports,Accessories,Dell,3.3,1311,551,99.8,Yes,NaN
1000122,PRD-NBP2,Hooded Sweatshirt,Clothing,Shoes,Asus,3.1,3941,543,25.9,Yes,NaN

In [17]:
new_df.describe().round(2)

,product_rating_avg,product_reviews_count,stock_quantity,fraud_risk_score
count,1000123.00,1000123.00,1000123.00,1000123.00
mean,4.00,2501.57,499.81,49.96
std,0.58,1443.46,288.86,28.85
min,3.00,0.00,0.00,0.00
25%,3.50,1253.00,250.00,25.00
50%,4.00,2503.00,500.00,50.00
75%,4.50,3752.00,750.00,74.90
max,5.00,5000.00,1000.00,100.00

### list of product_id(s) with distinct product_name(s) count

In [18]:
test = new_df.groupby('product_id')["product_name"].nunique().loc[lambda x : x>1]
test

product_id
PRD-0000    3
PRD-0008    3
PRD-0009    2
PRD-000D    2
PRD-000F    3
           ..
PRD-ZZYG    2
PRD-ZZYT    2
PRD-ZZYV    2
PRD-ZZZC    4
PRD-ZZZG    2
Name: product_name, Length: 198892, dtype: int64

In [19]:
test.iloc[:].sum()

439243

In [20]:
new_df.sort_values("product_id").head(20)

,product_id,product_name,category,sub_category,brand,product_rating_avg,product_reviews_count,stock_quantity,fraud_risk_score,support_ticket_created,return_reason
6338,PRD-0000,USB-C Fast Charger 65W,Electronics,Accessories,Adidas,5.0,4062,894,2.7,Yes,NaN
339447,PRD-0000,Laptop Backpack Waterproof,Electronics,Cameras,Baseus,3.4,1818,377,22.0,Yes,NaN
402918,PRD-0000,Water Bottle Insulated,Sports,Sports Wear,JBL,4.7,4317,646,52.1,No,NaN
402234,PRD-0001,Hooded Sweatshirt,Clothing,Shoes,Huawei,4.1,4806,74,48.1,No,NaN
55022,PRD-0003,Storage Box Set,Home,Decor,Adidas,4.3,1784,737,77.5,Yes,NaN
277145,PRD-0006,Fitness Smart Band,Health,Personal Care,HP,4.7,4552,615,49.3,Yes,Better Price Elsewhere
622329,PRD-0008,Storage Box Set,Home,Kitchen,Nikon,3.1,711,277,16.1,No,NaN
538839,PRD-0008,USB Hub 7-Port,Electronics,Tablets,Sony,3.6,4522,359,61.1,No,NaN
267173,PRD-0008,Foam Roller,Health,Supplements,Lenovo,4.2,4163,962,35.7,Yes,NaN
955210,PRD-0009,Swimming Goggles,Sports,Outdoor,Apple,4.8,3773,11,22.4,Yes,NaN
301222,PRD-0009,Bedsheet Set Cotton,Home,Furniture,Fitbit,3.3,2708,0,27.3,Yes,NaN
25519,PRD-000D,Jump Rope Speed,Sports,Sports Wear,JBL,4.9,4884,222,77.9,No,NaN
222620,PRD-000D,Wireless Mouse 2.4GHz,Electronics,Smartphones,Xiaomi,3.1,4284,645,65.6,No,NaN
909872,PRD-000E,Casual Sneakers,Clothing,Mens Wear,Dell,3.0,1397,525,55.5,Yes,NaN
587043,PRD-000F,Massage Gun Deep Tissue,Health,Supplements,Sony,3.8,1043,725,76.7,No,NaN
242922,PRD-000F,Desk Lamp LED,Home,Furniture,Adidas,3.0,204,147,42.6,No,NaN
13520,PRD-000F,Fitness Smart Band,Health,Fitness,Nikon,4.0,2248,133,34.9,No,NaN
551452,PRD-000H,Running Shoes Air Zoom,Clothing,Mens Wear,Adidas,4.2,698,598,61.5,Yes,NaN
642349,PRD-000K,Fitness Smart Band,Health,Supplements,Philips,4.5,2013,48,32.4,Yes,NaN
74771,PRD-000K,Vacuum Robot Cleaner,Home,Appliances,Sony,3.6,1727,461,75.5,No,NaN

### need to change the product_id of the duplicates in the new_df (ending with _int)

In [21]:
new_df.columns

Index(['product_id', 'product_name', 'category', 'sub_category', 'brand',
       'product_rating_avg', 'product_reviews_count', 'stock_quantity',
       'fraud_risk_score', 'support_ticket_created', 'return_reason'],
      dtype='object')

In [22]:
new_df[["product_rating_avg","product_reviews_count","stock_quantity"]].sort_values("product_rating_avg", ascending = False)

        product_rating_avg  product_reviews_count  stock_quantity
215664                 5.0                   1966             927
981878                 5.0                   1776              71
779647                 5.0                   1259              66
61494                  5.0                   2762             450
386466                 5.0                   3158             172
...                    ...                    ...             ...
495526                 3.0                   3895             900
310741                 3.0                   4305             719
157159                 3.0                   1841             458
157177                 3.0                    832             795
946960                 3.0                   1674             607

[1000123 rows x 3 columns]

### Final Data

In [23]:
df_final = df[['order_id', 'order_date',  'order_year', 'order_month', 'order_day',
       'order_hour', 'order_minute', 'order_second','is_weekend',
       'order_status', 'customer_id', 'customer_name',
       'gender', 'age', 'customer_segment', 'country', 'city',
       'customer_loyalty_score', 'total_orders_by_customer',
       'account_creation_date', 'product_id', 'product_name', 'category',
       'sub_category', 'brand', 'product_rating_avg', 'product_reviews_count',
       'stock_quantity', 'unit_price_usd', 'quantity', 'discount_percent',
        'total_price_usd', 'cost_usd', 'profit_usd',
       'tax_usd', 'payment_method', 'payment_status',
       'installment_plan', 'shipping_method', 'shipping_cost_usd',
       'delivery_days', 'shipping_country', 'warehouse_location',
       'delivery_status', 'device_type'
        ]]

In [24]:
df_final.isna().sum()

order_id                    0
order_date                  0
order_year                  0
order_month                 0
order_day                   0
order_hour                  0
order_minute                0
order_second                0
is_weekend                  0
order_status                0
customer_id                 0
customer_name               0
gender                      0
age                         0
customer_segment            0
country                     0
city                        0
customer_loyalty_score      0
total_orders_by_customer    0
account_creation_date       0
product_id                  0
product_name                0
category                    0
sub_category                0
brand                       0
product_rating_avg          0
product_reviews_count       0
stock_quantity              0
unit_price_usd              0
quantity                    0
discount_percent            0
total_price_usd             0
cost_usd                    0
profit_usd                  0
tax_usd                     0
payment_method              0
payment_status              0
installment_plan            0
shipping_method             0
shipping_cost_usd           0
delivery_days               0
shipping_country            0
warehouse_location          0
delivery_status             0
device_type                 0
dtype: int64

In [25]:
df_final['product_id'] = pd.factorize(df_final['product_name'])[0] + 1

C:\Users\SWARNAVA KUNDU\AppData\Local\Temp\ipykernel_784\3850374915.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final['product_id'] = pd.factorize(df_final['product_name'])[0] + 1

In [26]:
df_final["customer_id"] = df_final['customer_id'].astype(str) + '' + df_final.groupby('customer_id')['customer_name'].transform(lambda x: pd.factorize(x)[0]).astype(str)

C:\Users\SWARNAVA KUNDU\AppData\Local\Temp\ipykernel_784\1064608495.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final["customer_id"] = df_final['customer_id'].astype(str) + '' + df_final.groupby('customer_id')['customer_name'].transform(lambda x: pd.factorize(x)[0]).astype(str)

In [27]:
df_final['order_id'] = df_final['order_id'].astype(str) + '' + df_final.groupby('order_id').cumcount().astype(str)

C:\Users\SWARNAVA KUNDU\AppData\Local\Temp\ipykernel_784\3732978593.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final['order_id'] = df_final['order_id'].astype(str) + '' + df_final.groupby('order_id').cumcount().astype(str)

In [28]:
t1 = df_final.groupby('customer_id')["customer_name"].nunique().loc[lambda x : x>1]
t1

Series([], Name: customer_name, dtype: int64)

In [29]:
df_final["order_id"].nunique()-len(df)

0

In [30]:
df_final.shape

(1000123, 45)

In [ ]:
new_path = os.path.join("data","final_dataset.csv")
df_final.to_csv(new_path, index=False)